name: Release Workflow

on:
  push:
    branches:
      - 'release/*'

env:
  REGISTRY: meltoz
  IMAGE_NAME: lethal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Choisis la version de Node.js appropriée

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{env.REGISTRY}}
          password: ${{secrets.PASS_DOCKER}}

      - name: Extract version from branch name
        id: extract_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/heads/release/}"

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.extract_version.outputs.VERSION }} -f DockerFile .
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{ steps.extract_version.outputs.VERSION }}

      - name: Create tag on master branch
        run: |
          git fetch origin master
          git tag -a "v${{ steps.extract_version.outputs.VERSION }}" -m "Release version ${{ steps.extract_version.outputs.VERSION }}"
          git push origin "v${{ steps.extract_version.outputs.VERSION }}"

      - name: Delete release branch
        run: |
          git push origin --delete ${GITHUB_REF#refs/heads/release/}